//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entretien
    {
        public int IdEntretien { get; set; }
        public string TypeEntretien { get; set; }
        public Nullable<int> Kilometrage { get; set; }
        public Nullable<int> Num_Vehicule { get; set; }
    }
}
