//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparation
    {
        public int IdReparation { get; set; }
        public Nullable<System.DateTime> DateReparation { get; set; }
        public string Designation { get; set; }
        public string Quantite { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<decimal> MontantTotale { get; set; }
        public Nullable<int> Num_Vehicule { get; set; }
    }
}
