//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public int NumVehicule { get; set; }
        public string Matricule { get; set; }
        public string Marque { get; set; }
        public string Puissance { get; set; }
        public string Energie { get; set; }
        public Nullable<System.DateTime> DMC { get; set; }
        public Nullable<int> Num_Chassis { get; set; }
        public Nullable<int> NombrePlaces { get; set; }
        public string AgeMoyen { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<int> IdCategorie { get; set; }
        public Nullable<int> IdUT { get; set; }
    }
}
